### ISSUE TITLE
gr-pager doesn't build against GNURadio 3.8

### ISSUE THREAD

**Issue by troycurtisjr** [amboar/gr-pager#3]
This version of gr-pager doesn't build against 3.8, and it's more useful than ever to have it do so as it is now been removed from GNURadio core. I'll be posting a PR shortly for this, but wanted to get it recorded.

**Comment by amboar** [comment]
Hi @troycurtisjr! I don't have the capacity to maintain the repo, are you keen to take over? If so I'm happy to ack a change to the recipe in gr-etcetera to change the repo URL to point to your own fork.

I'd made a bunch of changes to the code structure of the decoder a long time back. Part of it was to help clarify the code, but it traded performance for some readability. I also added support for split message concatenation, though that has some bugs that need to be resolved. Essentially I don't think it's clear that my changes improved the plugin :)

Let me know how you want to work with it.

**Comment by troycurtisjr** [comment]
Ah! haha I can understand that. Sure, we can repoint the repo. We'll see how long I keep up with it, but at the very least it will keep it going for a bit longer. I'll stage a PR in the next few days on gr-etcetera and ping you on it.

**Comment by troycurtisjr** [comment]
Repo now available at https://github.com/troycurtisjr/gr-pager as a GNURadio 3.8 OOT module.

**Comment by amboar** [comment]
Thanks @troycurtisjr!
